; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
framework = arduino
monitor_speed = 115200


[env:checkpoint_8266]
platform = espressif8266
board = esp12e
lib_deps = 
    adafruit/Adafruit Unified Sensor@^1.1.15
    https://github.com/adafruit/Adafruit_ADXL345.git


build_src_filter = 
    +<main_esp8266_checkpoint.cpp>
    +<esp8266_checkpoint_deps/>


[env:serveur]
platform = espressif8266
board = esp12e

build_src_filter = 
    +<main_serveur.cpp>
    +<serveur_deps/>


[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
lib_deps = 
	https://github.com/Arduino-IRremote/Arduino-IRremote.git@ ^4.4.0
	bblanchon/ArduinoJson @ ^7.4.3
	arduino-libraries/SD@ ^1.2.4
    arduino-libraries/LiquidCrystal@ ^1.0.7

build_src_filter = 
    +<main_mega.cpp>
    +<mega_deps/>